spring:
  application:
    name: 37-sopkathon
  profiles:
    group:
      local: local-db, local-port, common
      dev : dev-db, dev-port, common
    active: ${ACTIVE_PROFILE}

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
openai:
  secret-key: ${OPEN_AI_KEY}
  model: ${OPEN_AI_MODEL}
  max-tokens: ${OPEN_AI_MAX_TOKEN}
  temperature: ${OPEN_AI_TEMPERATURE}
  base-url: https://api.openai.com/v1
---
spring:
  config:
    activate:
      on-profile: local-db
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: local-port
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev-db
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev-port
server:
  port: 8080